name: R_parsing
channels:
 - conda-forge
 - bioconda
 - defaults
 - conda-forge/label/broken
dependencies:
 - r-base
# - rstudio-desktop=2022.12.0
 - r-xlsx
 - r-gtable
 - r-gplots
 - r-stringr
 - r-tidyr
 - r-ggplot2
 - r-plotly
 - r-gridextra 
 - r-pheatmap
 - r-rmarkdown
 - r-knitr
 - r-reshape2
 - r-quarto
 - r-palmerpenguins
 - r-tidyverse
 - r-reactable
 - r-bookdown