---
title: "Training Survey Overview"
format: 
  html:
    toc: true
    number-sections: true
    css: styles.css
    fig-align: center
    fig-width: 8
    fig-height: 5.5 
    code-tools: true
    embed-resources: true
editor: visual
execute: 
  echo: false
  message: false
  warning: false
  error: false
---

```{r}

suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(xlsx))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(pheatmap))
suppressPackageStartupMessages(library(reactable))
suppressPackageStartupMessages(library(htmltools))
```

```{r}
#| output: false
library(palmerpenguins)
data(package = 'palmerpenguins')
ojs_define(data = penguins)
```

```{ojs}
viewof bill_length_min = Inputs.range(
  [32, 50], 
  {value: 35, step: 1, label: "Bill length (min):"}
)
viewof islands = Inputs.checkbox(
  ["Torgersen", "Biscoe", "Dream"], 
  { value: ["Torgersen", "Biscoe"], 
    label: "Islands:"
  }
)
```

```{ojs}
filtered = data.filter(function(penguin) {
  return bill_length_min < penguin.bill_length &&
         islands.includes(penguin.island);
})
```

```{ojs}
Plot.rectY(filtered, 
  Plot.binX(
    {y: "count"}, 
    {x: "body_mass", fill: "species", thresholds: 20}
  ))
  .plot({
    facet: {
      data: filtered,
      x: "sex",
      y: "species",
      marginRight: 80
    },
    marks: [
      Plot.frame(),
    ]
  }
)
```

```{r, echo=FALSE, results='hide'}
sessionInfo()
```